### ISSUE TITLE
Change the default (hard coded) domain search list: `gateway-it.internal`

### ISSUE THREAD

**Issue by yaroslav-gwit** [yaroslav-gwit/HosterCore#6]
The code block below should be changed to pick up a system hostname, and add `.internal.lan` suffix to make it more dynamic.

```
const ciNetworkConfigTemplate = `version: 2
ethernets:
  interface0:
     match:
       macaddress: "{{ .MacAddress }}"
     
     set-name: eth0
     addresses:
     - {{ .IpAddress }}/{{ .NakedSubnet }}
     
     gateway4: {{ .Gateway }}
     
     nameservers:
       search: [ gateway-it.internal, ]
       addresses: [ {{ .Gateway }}, ]
`
```
